name: Trivy Security Scan

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  scan-terraform:
    name: Scan Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Trivy on Terraform
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: terraform
          exit-code: 1
          severity: HIGH,CRITICAL
          trivyignores: terraform/.trivyignore

  scan-images:
    name: Scan ${{ matrix.image }} image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image: [go-todo-app, web]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Scan image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.image }}:latest
          exit-code: 1
          severity: HIGH,CRITICAL
          ignore-unfixed: true